# this will compile the New_Alarm_Cond.C file using c compiler create an
# executable file called "a3"
New_Alarm_Cond:	New_Alarm_Cond.c
	cc -o a3 New_Alarm_Cond.c -D_POSIX_PTHREAD_SEMANTICS -lpthread

clean:
	rm a3
